
server:  port: 8081
  
spring:
  application:
    name: 'fornecedor'  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:alura-forum
    username: sa    password: 
  jpa:    hibernate:      ddl-auto: update    database-platform: org.hibernate.dialect.H2Dialect
  h2:    console:      enabled: true      path: /h2-console
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka